[package]
name = "blah"
version = "0.1.0"
authors = ["Hamish Hutchings <moredhel@aoeu.me>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
